name: mahmoodi-pix2pixhd
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - cudatoolkit=10.1
  - scipy
  - tensorboard
  - pillow
  - numpy
  - scikit-image=0.19.2
  - pip:
      - torch==1.7.1+cu101
      - torchvision==0.8.2+cu101
      - torchaudio==0.7.2
      - dominate==2.4.0
      - visdom==0.1.8
      - --find-links https://download.pytorch.org/whl/torch_stable.html
