name: mahmoodi-pix2pixhd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - scipy
  - tensorboard
  - pip:
    - torchvision==0.5.0
    - dominate==2.4.0
    - Pillow==6.1.0
    - numpy==1.16.4
    - visdom==0.1.8
