name: mahmoodipix2pixhd
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=12.4
  - scipy
  - tensorboard
  - pillow
  - numpy
  - scikit-image=0.24.0
  - pip:
      - torch==2.5.0
      - torchvision==0.20.0
      - torchaudio==2.5.0
      - dominate==2.9.1
      - visdom==0.2.4


